// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RepricerPriceDataApiClientTypes.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GetPriceQueryResultRequest
    {
        /// <summary>
        /// Initializes a new instance of the GetPriceQueryResultRequest class.
        /// </summary>
        public GetPriceQueryResultRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetPriceQueryResultRequest class.
        /// </summary>
        public GetPriceQueryResultRequest(UserCredentialBag userBag = default(UserCredentialBag), string token = default(string))
        {
            UserBag = userBag;
            Token = token;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserBag")]
        public UserCredentialBag UserBag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Token")]
        public string Token { get; set; }

    }
}
