// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RepricerPriceDataApiClientTypes.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PricedOfferWithAttribute
    {
        /// <summary>
        /// Initializes a new instance of the PricedOfferWithAttribute class.
        /// </summary>
        public PricedOfferWithAttribute()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PricedOfferWithAttribute class.
        /// </summary>
        public PricedOfferWithAttribute(bool isMyOffer, bool isAmazon, PricedOffer offer = default(PricedOffer), string merchantId = default(string))
        {
            Offer = offer;
            IsMyOffer = isMyOffer;
            IsAmazon = isAmazon;
            MerchantId = merchantId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Offer")]
        public PricedOffer Offer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsMyOffer")]
        public bool IsMyOffer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsAmazon")]
        public bool IsAmazon { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MerchantId")]
        public string MerchantId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Offer != null)
            {
                Offer.Validate();
            }
        }
    }
}
