// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RepricerPriceDataApiClientTypes.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SalesRank
    {
        /// <summary>
        /// Initializes a new instance of the SalesRank class.
        /// </summary>
        public SalesRank()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SalesRank class.
        /// </summary>
        public SalesRank(int rankkBackingField, string productCategorykBackingField = default(string))
        {
            ProductCategorykBackingField = productCategorykBackingField;
            RankkBackingField = rankkBackingField;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "<ProductCategory>k__BackingField")]
        public string ProductCategorykBackingField { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "<Rank>k__BackingField")]
        public int RankkBackingField { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
