// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RepricerPriceDataApiClientTypes.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SubApiItemReadResult
    {
        /// <summary>
        /// Initializes a new instance of the SubApiItemReadResult class.
        /// </summary>
        public SubApiItemReadResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubApiItemReadResult class.
        /// </summary>
        public SubApiItemReadResult(int readFailedReason, int errorCode, PricedOffersResultWithAttribute priceResult = default(PricedOffersResultWithAttribute))
        {
            ReadFailedReason = readFailedReason;
            ErrorCode = errorCode;
            PriceResult = priceResult;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReadFailedReason")]
        public int ReadFailedReason { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ErrorCode")]
        public int ErrorCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PriceResult")]
        public PricedOffersResultWithAttribute PriceResult { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (PriceResult != null)
            {
                PriceResult.Validate();
            }
        }
    }
}
