// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RepricerPriceDataApiClientTypes.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SubmitAsinsForQueryRequest
    {
        /// <summary>
        /// Initializes a new instance of the SubmitAsinsForQueryRequest class.
        /// </summary>
        public SubmitAsinsForQueryRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubmitAsinsForQueryRequest class.
        /// </summary>
        public SubmitAsinsForQueryRequest(UserCredentialBag userBag = default(UserCredentialBag), IList<string> asins = default(IList<string>))
        {
            UserBag = userBag;
            Asins = asins;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserBag")]
        public UserCredentialBag UserBag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asins")]
        public IList<string> Asins { get; set; }

    }
}
