// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RepricerPriceDataApiClientTypes.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UserCredentialBag
    {
        /// <summary>
        /// Initializes a new instance of the UserCredentialBag class.
        /// </summary>
        public UserCredentialBag()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserCredentialBag class.
        /// </summary>
        public UserCredentialBag(string authenKey = default(string), string userID = default(string), string password = default(string), string sellerID = default(string), string marketplaceID = default(string))
        {
            AuthenKey = authenKey;
            UserID = userID;
            Password = password;
            SellerID = sellerID;
            MarketplaceID = marketplaceID;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AuthenKey")]
        public string AuthenKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserID")]
        public string UserID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SellerID")]
        public string SellerID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MarketplaceID")]
        public string MarketplaceID { get; set; }

    }
}
